#!/usr/bin/env bash
# =============================================================================
#  IoT Modular System — self-hosted quick installer
# =============================================================================
#  Runs on a fresh Ubuntu/Debian/Fedora server (root or via sudo).
#  What it does:
#
#    1. Installs Docker Engine + docker compose plugin if missing.
#    2. Generates .env interactively (or reuses an existing one).
#    3. Opens firewall ports: 80, 443 (web/TLS), 1883, 9001 (MQTT).
#    4. Builds and starts the whole stack (server + mosquitto + nginx + certbot).
#
#  Usage:   sudo bash install.sh
#  Re-run:  keeps the existing .env and just recreates containers.
#
# =============================================================================
set -euo pipefail

GREEN='\033[1;32m'; YELLOW='\033[1;33m'; RED='\033[1;31m'; NC='\033[0m'
log()  { echo -e "${GREEN}[iot-selfhost]${NC} $*"; }
warn() { echo -e "${YELLOW}[iot-selfhost]${NC} $*"; }
die()  { echo -e "${RED}[iot-selfhost] ERROR:${NC} $*" >&2; exit 1; }

# Run everything from the repo root (works when invoked from anywhere).
cd "$(dirname "$0")"
[ -f docker-compose.yml ] || die "docker-compose.yml not found — run from the repo root"

# ----------------------------------------------------------------------
require_root() {
  [ "$(id -u)" -eq 0 ] || die "run as root: sudo bash install.sh"
}

# ----------------------------------------------------------------------
install_docker() {
  if command -v docker >/dev/null 2>&1; then
    log "docker: $(docker --version) (already installed)"
  else
    log "docker not found, installing via get.docker.com..."
    command -v curl >/dev/null 2>&1 || die "curl is required — install it: sudo apt install curl"
    curl -fsSL https://get.docker.com | sh
  fi

  systemctl enable --now docker >/dev/null 2>&1 || true
  systemctl start docker >/dev/null 2>&1 || true

  if docker compose version >/dev/null 2>&1; then
    log "docker compose plugin: $(docker compose version | awk '{print $2}') (ok)"
  else
    log "docker compose plugin missing, installing..."
    mkdir -p /usr/local/lib/docker/cli-plugins
    curl -fsSL "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-$(uname -m)" \
      -o /usr/local/lib/docker/cli-plugins/docker-compose
    chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
    docker compose version >/dev/null 2>&1 || die "failed to install docker compose"
    log "docker compose plugin installed: $(docker compose version | awk '{print $2}')"
  fi
}

# ----------------------------------------------------------------------
gen_env() {
  [ -f .env ] && { warn ".env already exists — keeping it (edit it to change settings)"; return; }

  log "Let's configure the deployment. Empty values can be typed later into .env."
  read -r -p "  Domain name (FQDN -> this server, e.g. iot.example.com) [localhost]: " DOMAIN
  DOMAIN="${DOMAIN:-localhost}"

  read -r -p "  Enable HTTPS via Let's Encrypt? (y/n) [y]: " TLS
  TLS="$(echo "${TLS:-y}" | tr '[:upper:]' '[:lower:]')"
  [ "$TLS" = "y" ] || [ "$TLS" = "n" ] || die "answer y or n"
  NGINX_TLS=$([ "$TLS" = "y" ] && echo 1 || echo 0)
  local EMAIL=""
  if [ "$NGINX_TLS" = "1" ]; then
    read -r -p "  Email for Let's Encrypt (required with HTTPS): " EMAIL
    [ -n "$EMAIL" ] || die "email is required when HTTPS is enabled"
  fi

  read -r -p "  API register token (used by devices + app): " TOKEN
  TOKEN="${TOKEN:-$(head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 24)}"
  log "  register token set ($(echo -n "$TOKEN" | wc -c) chars)"

  read -r -p "  MQTT app username [app]: " MQTT_USER; MQTT_USER="${MQTT_USER:-app}"
  read -r -p "  MQTT app password: " MQTT_PASSWORD
  [ -n "$MQTT_PASSWORD" ] || MQTT_PASSWORD="$(head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 24)"
  read -r -p "  MQTT device username [device]: " MQTT_DEVICE_USER; MQTT_DEVICE_USER="${MQTT_DEVICE_USER:-device}"
  read -r -p "  MQTT device password: " MQTT_DEVICE_PASSWORD
  [ -n "$MQTT_DEVICE_PASSWORD" ] || MQTT_DEVICE_PASSWORD="$(head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 24)"

  cat > .env <<EOF
# Generated by install.sh on $(date -u +%F\ %TZ). Edit here to change settings, then: docker compose up -d.
NGINX_DOMAIN=$DOMAIN
NGINX_TLS=$NGINX_TLS
CERTBOT_EMAIL=$EMAIL
REGISTER_TOKEN=$TOKEN
MQTT_USER=$MQTT_USER
MQTT_PASSWORD=$MQTT_PASSWORD
MQTT_DEVICE_USER=$MQTT_DEVICE_USER
MQTT_DEVICE_PASSWORD=$MQTT_DEVICE_PASSWORD
PORT=3100
STALE_MS=180000
RATE_LIMIT_WINDOW_MS=60000
EOF
  chmod 600 .env
  log ".env written"
}

# ----------------------------------------------------------------------
open_firewall() {
  local PORTS=(80 443 1883 9001)
  if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -qwi active; then
    for p in "${PORTS[@]}"; do ufw allow "${p}/tcp" >/dev/null; done
    log "ufw: allowed ${PORTS[*]}"
  elif command -v firewall-cmd >/dev/null 2>&1 && systemctl is-active firewalld >/dev/null 2>&1; then
    for p in "${PORTS[@]}"; do firewall-cmd --permanent --add-port="${p}/tcp" >/dev/null; done
    firewall-cmd --reload >/dev/null
    log "firewalld: allowed ${PORTS[*]}"
  else
    warn "no active firewall (ufw/firewalld) found — make sure ports 80/443/1883/9001 are open"
  fi
}

# ----------------------------------------------------------------------
start_stack() {
  source .env >/dev/null 2>&1 || true
  log "building images (first run may take a few minutes)..."
  if [ "${NGINX_TLS:-0}" = "1" ]; then
    docker compose --profile certbot up -d --build
    warn "HTTPS: first certificate is issued in the background; wait a few minutes, then visit https://${NGINX_DOMAIN:-localhost}"
  else
    docker compose up -d --build
  fi

  log "waiting for the API to become healthy..."
  for i in $(seq 1 30); do
    if curl -fsS http://127.0.0.1/api/v1/health >/dev/null 2>&1; then
      log "API is up."; return
    fi
    sleep 2
  done
  warn "API did not respond in 60s — check: docker compose ps / docker compose logs -f"
}

# ----------------------------------------------------------------------
print_summary() {
  source .env
  local BASE="http://${NGINX_DOMAIN:-localhost}"
  [ "${NGINX_TLS:-0}" = "1" ] && BASE="https://${NGINX_DOMAIN:-localhost}"

  echo
  echo "==============================================================="
  echo "  IoT Modular System — self-hosted is running"
  echo "==============================================================="
  echo "  Web / OTA:     $BASE"
  echo "  API health:    $BASE/api/v1/health"
  echo "  MQTT:          ${NGINX_DOMAIN:-localhost}:1883 (app / devices)"
  echo "  MQTT ws:       ${NGINX_DOMAIN:-localhost}:9001"
  echo
  echo "  App settings:"
  echo "    API URL:         $BASE/api/v1"
  echo "    Register token:  (see .env REGISTER_TOKEN)"
  echo "    MQTT server:     ${NGINX_DOMAIN:-localhost}  user: ${MQTT_USER}  (pass in .env)"
  echo "    OTA URL:         $BASE/fw"
  echo
  echo "  Device firmware (config.h):"
  echo "    SERVER_URL = $BASE"
  echo "    mqtt_user  = $MQTT_DEVICE_USER  (pass in .env)"
  echo
  echo "  Daily ops: docker compose ps | logs -f | down   (run in $(pwd))"
  echo "==============================================================="
}

# ----------------------------------------------------------------------
main() {
  require_root
  install_docker
  gen_env
  open_firewall
  start_stack
  print_summary
}

main "$@"